# Generated by Django 2.0.2 on 2018-11-05 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dbaloginuser',
            fields=[
                ('db_user_id', models.CharField(help_text='Enter Database User id', max_length=20, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=200)),
                ('username', models.CharField(blank=True, help_text='Enter username', max_length=100)),
                ('user_type', models.CharField(blank=True, help_text='Enter username as monitor,dba,apps', max_length=100)),
                ('user_status', models.CharField(choices=[('A', 'Active'), ('I', 'InActive')], default='A', help_text='status A - active, I - Inactive', max_length=1)),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('comments', models.CharField(blank=True, help_text='Enter comments if any', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dbamenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField()),
                ('task_name', models.CharField(max_length=100)),
                ('task_summary', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['task_number'],
            },
        ),
    ]
