# Generated by Django 2.0.2 on 2018-11-11 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbawebmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbamenu',
            name='task_sqlquery',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
