# Generated by Django 2.0.2 on 2018-12-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbawebmenu', '0002_dbamenu_task_sqlquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbamenu',
            name='id',
        ),
        migrations.AlterField(
            model_name='dbamenu',
            name='task_number',
            field=models.IntegerField(help_text='Enter task number', primary_key=True, serialize=False),
        ),
    ]
